; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:unihiker]
platform = https://github.com/DFRobot/platform-unihiker.git
board = unihiker_k10
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
; Change -DNO_example to -Dexample to choose which example to build
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DModel=None
    -DNO_DISPLAY_BACKGROUND_COLOR
    -DNO_DISPLAY_PHOTO_ALBUM
    -DNO_DISPLAY_SHOWING_TEXT
    -DNO_DISPLAY_DRAW_POINT
    -DNO_DISPLAY_DRAW_LINE
    -DNO_DISPLAY_METEOR_SHOWER
    -DNO_DISPLAY_DRAW_RECTANGLE
    -DNO_DISPLAY_DRAW_CIRCLE
    -DNO_DISPLAY_QR_CODE
    -DNO_SENSOR_BUTTON_POLLING
    -DSENSOR_BUTTON_INTERRUPT